core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from .views import HomeView
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home_url"),
    path('signup/', SignupView.as_view(), name="signup_url"),
    path('login/', LoginView.as_view(), name="login_url"),
    path('logout/', logout_view, name="logout_url"),
    path('profile/', ProfileView.as_view(), name="profile_url"),
    path('add-personal-info/', PersonalInfoView.as_view(), name="personal_info_url"),
    path('verify-phone/', OtpView.as_view(), name='otp_url'),
    path('retotp/<str:phone>', ret_otp),
    path('manage-requests/', manage_requests, name="manage_requests_url"),
    path('delete-user/<int:id>', delete_user, name="delete_user_url"),
    path('export-csv/', export_csv, name="export-csv-url"),
    path('user-detail/<int:id>/', user_detail, name="user_detail_url"),
    path('handle-message', handle_message, name="handle_message_url")
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField
from django.db import models
from random import randint
import os
# different images upload paths: 

def document_upload(instance, file):
    name, ext = os.path.splitext(os.path.basename(file))
    return f'users/documents/{instance.id}{ext}'

def fish_upload(instance, file):
    name, ext = os.path.splitext(os.path.basename(file))
    return f'users/fishs/{instance.id}{ext}'

def profile_upload(instance, file):
    name, ext = os.path.splitext(os.path.basename(file))
    return f'users/profile/{instance.id}-{randint(0, 99)}{ext}'

class UserManager(BaseUserManager):
    def create_user(self, phone_number, password=None, **extra_fields):
        user = self.model(
            phone_number=phone_number
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone_number, password=None, **extra_fields):
        user = self.create_user(
            phone_number=phone_number,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):

    phone_number = PhoneNumberField(region='IR', unique=True)
    is_admin     = models.BooleanField(default=False)
    is_verified  = models.BooleanField(default=False)

    objects         = UserManager()
    USERNAME_FIELD  = 'phone_number'


    def __str__(self) -> str:
        return str(self.phone_number)
    
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    
    @property
    def is_staff(self):
        return self.is_admin
    
class OtpContainer(models.Model):
    otpCode = models.CharField('OTP Code', max_length=6 , blank=True,)
    user    = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="otp")

    def __str__(self):
        return f'{self.otpCode} - {self.user}'

# we using ProfileModel in PersonalInfoView view class
class ProfileModel(models.Model):
    first_name = models.CharField(max_length=60)
    last_name  = models.CharField(max_length=60)
    national_code = models.IntegerField(null=True, blank=True)
    email_address = models.EmailField(null=True, blank=True)
    address       = models.TextField(null=True, blank=True)
    profile_pic   = models.ImageField(upload_to=profile_upload, null=True, blank=True, default='/media/site/avatar.svg')
    user          = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="profile", related_name="profile")

    def __str__(self) -> str:
        return str(self.first_name + ' ' + self.last_name)
    
class PaymentModel(models.Model):
    amount        = models.IntegerField(null=True, blank=True)
    card          = models.IntegerField(null=True, blank=True)
    shaba         = models.CharField(max_length=25,null=True, blank=True)
    document      = models.ImageField(upload_to=document_upload, null=True, blank=True)
    fish          = models.ImageField(upload_to=fish_upload, null=True, blank=True)
    user          = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="payment", related_name="payment")

    def __str__(self):
        return str(self.id)
    

class Messages(models.Model):
    email = models.CharField(max_length=90)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email
    

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from phonenumber_field.formfields import RegionalPhoneNumberWidget
from .models import User, ProfileModel, PaymentModel

class UserForm(forms.ModelForm):
    password =  forms.CharField(max_length=12, widget=forms.PasswordInput(attrs={'class':'form-control w-75 my-2', 'placeholder':'رمز عبور خود را وارد کنید', 'name': 'password', 'id':'password'}))
    class Meta:
        model = User
        fields = ['phone_number']
        widgets = {
            'phone_number':RegionalPhoneNumberWidget(region='IR', attrs={'class':'form-control w-75 my-2', 'placeholder':'شماره تلفن همراه خود را وارد کنید', 'id':'phone_number'})
        }

    def clean(self):
        cd = self.cleaned_data
        if cd['phone_number'] and cd['password']:
            return cd
        else:
            raise ValidationError("You have to fill both fields of phone number and password!")

    def save(self, commit=False):
        instance = super().save(commit)
        cd = super().clean()
        instance.set_password(cd['password'])
        instance.save()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = ProfileModel
        fields = ['first_name', 'last_name', 'national_code', 'email_address', 'address', 'profile_pic']
        widgets = {
            'first_name': forms.TextInput(attrs={'class':'form-control my-3 w-75', 'placeholder':'نام خود را وارد کنید'}),
            'last_name': forms.TextInput(attrs={'class':'form-control my-3 w-75', 'placeholder':'نام خانوادگی خود را وارد کنید'}),
            'national_code': forms.TextInput(attrs={'class':'form-control my-3 w-75', 'placeholder':'کد ملی خود را وارد کنید'}),
            'email_address': forms.TextInput(attrs={'class':'form-control my-3 w-75', 'placeholder':'آدرس ایمیل خود را وارد کنید'}),
            'address': forms.TextInput(attrs={'class':'form-control my-3 w-75', 'placeholder':'آدرس محل سکونت خود را وارد کنید'}),
            'profile_pic': forms.FileInput(attrs={'class':'form-control my-3 w-75'})
        }
        labels = {
            'profile_pic': 'عکس پروفایل کاربری',
            'first_name':'',
            'last_name':'',
            'national_code':'',
            'email_address':'',
            'address':'',
        }

class PaymentForm(forms.ModelForm):
    class Meta: 
        model = PaymentModel
        fields = ['amount', 'card', 'shaba', 'document', 'fish']
        widgets = {
            'amount': forms.TextInput(attrs={'class':'form-control my-3 w-75', 'placeholder':'مقدرا درخواستی خود را وارد کنید'}),
            'card': forms.TextInput(attrs={'class':'form-control my-3 w-75', 'placeholder':'شماره کارت خود را وارد کنید'}),
            'shaba': forms.TextInput(attrs={'class':'form-control my-3 w-75', 'placeholder':'شماره شبا خود را وارد کنید'}),
            'document': forms.FileInput(attrs={'class':'form-control my-3 w-75 d-none'}),
            'fish': forms.FileInput(attrs={'class':'form-control my-3 w-75 d-none'}),
        }
        labels = {
            'amount':'',
            'card':'',
            'shaba':'',
            'document':'',
            'fish':''
        }

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.messages import success, error
from .forms import UserForm, ProfileForm, PaymentForm, ProfileModel
from .models import User, PaymentModel, Messages
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponse, JsonResponse
from .utils import generate_otp
from .decorators import is_admin, is_get, login_required, is_post
import csv

# Create your views here.


class SignupView(View):

    def get(self, request):
        form = UserForm()
        return render(request, 'signup.html', {'form':form})
    
    def post(self, request):
        user = UserForm(request.POST)

        
        if user.is_valid():
            cd = user.cleaned_data
            if User.objects.filter(phone_number=cd['phone_number']).exists():
                error(request, 'قبلا کاربری با این شماره تلفن در سیستم ثبت شده است', extra_tags='danger')
                return redirect('signup_url')
            user.save()
        else:
            print('something went wrong')
        success(request, "ثبت شما با موفقیت انجام شد جهت ادامه شماره همراه خود را از طریق کد پیامکی تایید کنید.", extra_tags='success')
        return redirect('login_url')


class LoginView(View):
    def get(self, request):
        
        return render(request, 'login.html')
    
    def post(self, request):
        phone_number = request.POST['phone_number']
        password = request.POST['password']
        
        if str(phone_number).startswith('0'):
            pn = str(phone_number)
            phone_number = '+98' + pn[1:]

        if phone_number and password:
            user = authenticate(phone_number=phone_number, password=password)
            if user:
                login(request, user)
                success(request, 'شما با موفقیت وارد سیستم شدید!', extra_tags='success')
                return redirect('otp_url')
            else:
                error(request, 'شماره همراه یا رمز عبور اشتباه می باشد', extra_tags="danger")
                return redirect('login_url')
        error(request, 'برای ورود به حساب کاربری هر دو فیلد را باید پر کنید', extra_tags="danger")
        return redirect('login_url')

def logout_view(request):
    logout(request)
    error(request, "شما با موفقیت از سیستم خارج شدید", extra_tags="danger")
    return redirect('home_url')

class ProfileView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            error(request, "شما باید برای دسترسی به این صفحه ابتدا وارد حساب کاربری خود شوید.", extra_tags="danger")
            return redirect('home_url')
        user = User.objects.get(id=request.user.id)
        return render(request, 'profile.html', {'user_':user})
    

class PersonalInfoView(View):

    def get(self, request):
        if request.user.profile.first_name != "":
            return redirect('profile_url')
        profile_form = ProfileForm()
        payment_form = PaymentForm()
        # print(request.user)
        return render(request, 'personalinfo.html', {'profile_form': profile_form, 'payment_form':payment_form})
    def post(self, request):
        user = User.objects.get(id = request.user.id)
        payment = PaymentModel.objects.get(user__id=user.id)
        profile = ProfileModel.objects.get(user__id=user.id)
        payment_form = PaymentForm(request.POST, files=request.FILES)
        profile_form = ProfileForm(request.POST, files=request.FILES)
        if payment_form.is_valid() and profile_form.is_valid():
            cd_pay = payment_form.cleaned_data
            cd_pro = profile_form.cleaned_data
            payment.amount = cd_pay['amount']
            payment.card   = cd_pay['card']
            payment.shaba   = cd_pay['shaba']
            payment.document = cd_pay['document']
            payment.fish = cd_pay['fish']
            payment.save()
            profile.first_name = cd_pro['first_name']
            profile.last_name = cd_pro['last_name']
            profile.national_code = cd_pro['national_code']
            profile.email_address = cd_pro['email_address']
            profile.address = cd_pro['address']
            profile.profile_pic = cd_pro['profile_pic']
            profile.save()
            # PaymentModel.objects.update(amount=cd_pay['amount'], card=cd_pay['card'], shaba=cd_pay['shaba'], document=cd_pay['document'], fish=cd_pay['fish'], user=user)
            # ProfileModel.objects.update(first_name=cd_pro['first_name'], last_name=cd_pro['last_name'], national_code=cd_pro['national_code'], email_address=cd_pro['email_address'], address=cd_pro['address'], profile_pic=cd_pro['profile_pic'], user=user)
            success(request, "ثبت و ارسال اطالاعات شما با موفقیت انجام شد پس از تایید اطلاعات از طریق پیامک به شما اطلاع رسانی خواهد شد.", extra_tags="success")
            return redirect('home_url')
        return redirect('personal_info_url')
    
class OtpView(View):
    def get(self, request):
        if request.user.is_verified:
            return redirect('personal_info_url')
        return render(request, 'otp_verification.html', {'phone': request.user.phone_number})
    
    def post(self, request):
        otp_code = request.POST['otp_code']
        user = User.objects.get(id=request.user.id)
        if otp_code == user.otpcontainer.otpCode:
            user.is_verified = True
            user.save()
            success(request, "تایید شماره شما با موفقیت انجام شد. هم اکنون جهت درخواست وام میتوانید اطلاعات پروفایل خود را تکمیل کنید", extra_tags="success")
            return redirect("personal_info_url")
        else:
            error(request, "در روند تایید شماره همراه شما مشکلی به وجود آمده دوباره تلاش کنید", extra_tags="danger")
            return redirect('otp_url')
    
@api_view(['get'])
def ret_otp(request, phone):
    otp_code = generate_otp(phone)
    return Response({'otp_code':otp_code})
    
@login_required
@is_admin
@is_get
def manage_requests(request):
    profiles = ProfileModel.objects.all()
    payments = PaymentModel.objects.all()
    return render (request,'requests.html', {'profiles':profiles, 'payments':payments})

@is_admin
def delete_user(request, id):
    user = User.objects.get(id=id)
    user.delete()
    success(request, 'کاربر با موفقیت حذف شد', extra_tags='danger')
    return redirect(request.META['HTTP_REFERER'])

def export_csv(request):
    users = User.objects.all()
    data = [
        ['نام', 'نام خانوادگی', 'آدرس ایمیل', 'شماره همراه', 'آدرس محل سکونت', 'شماره کارت', 'شماره شبا', 'مقدار درخواستی'],
    ] + [[_user.profile.first_name, _user.profile.last_name, _user.profile.email_address, _user.phone_number.national_number, _user.profile.address, _user.payment.card, _user.payment.shaba, _user.payment.amount] for _user in users]
    print(data)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="exported_data.csv"'
    writer = csv.writer(response)
    for row in data:
        writer.writerow(row)
    success(request, 'خروجی فایل csv با موفقیت ذخیره و دانلود شد.', extra_tags='success')
    return response

@login_required
@is_admin
def user_detail(request, id):
    user = get_object_or_404(User, id=id)
    return render(request, 'profile.html', {'user_':user, 'is_admin':True})

@is_post
def handle_message(request):
    try:
        Messages.objects.create(email=request.POST['email'], description = request.POST['description'])
        success(request, "پیام شما با موفقیت در سامانه ثبت شد به زودی با شما ارتباط میگیریم.", extra_tags="success")
        return redirect(request.META['HTTP_REFERER'])
    except:
        error(request,"خطا در ارسال پیام.",extra_tags="danger")
        return redirect(request.META['HTTP_REFERER'])

users/templates/login.html
{% extends 'base.html' %}

{% block title %}تایید شماره تلفن{% endblock title %}

{% block content %}
<div class="container-lg">
    <div class="p-5">
        <div class="d-flex justify-content-center">
            <form class="w-50" method='post'>
                {% csrf_token %}
                <input type="text" class="w-100 form-control my-3 text-center" name="phone_number" placeholder="شماره همراه خود را وارد کنید">
                <input type="password" class="w-100 form-control my-3 text-center" name="password" placeholder="رمز عبور خود را وارد کنید">
                <div class="d-grid gap-2 w-100">
                    <button type="submit" class="btn btn-success mt-1 p-3">ورود به حساب کاربری</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/otp_verification.html
{% extends 'base.html' %}

{% block title %}تایید شماره تلفن{% endblock title %}

{% block content %}
<div class="container-lg">
    <div class="p-5">
        <div class="d-flex flex-wrap justify-content-center">
            <form method="post" class="w-50">
                {% csrf_token %}
                <input type="text" name="otp_code" class="w-100 form-control text-center" placeholder="کد دریافتی خود را وارد کنید">
                <div class="d-grid gap-2 w-100 mt-5">
                    <button type="submit" class="btn btn-success p-3 mt-2">تایید شماره</button>
                </div>
            </form>
            <div class="w-100 d-flex justify-content-center">
                <div class="w-50">
                    <div class="d-grid gap-2 w-100 mt-2">
                        <button class="btn btn-primary p-3" onclick="sendotp({{phone}})">ارسال کد</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/personalinfo.html
{% extends 'base.html' %}

{% block title %}ثبت نام در سایت{% endblock title %}

{% block style %}
#form-input-wrapper-1 {
    display: flex ;
}

#form-input-wrapper-2, #form-input-wrapper-3, #form-input-wrapper-4, #form-input-wrapper-5 {
    display: none ;
}

#submit-form {
    display: none;
}

#back-button {
    display: none;
}

#doc_input, #fish_input {
    display: none;
}
{% endblock style %}

{% block content %}

<div class="container-lg">
    <div class="p-5 d-lg-flex">
        <div class="form-wrapper col-lg-6 col-12">
            <div class="form-container mt-5">
                <form class="d-flex justify-content-center flex-wrap pe-5" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div id="form-input-wrapper-1" class="w-100 justify-content-center flex-wrap">
                        <div class="heading-wrapper d-lg-none text-center w-100">
                            <h2>اطلاعات پروفایل</h2>
                        </div>
                        {{ profile_form.first_name }}
                        {{ profile_form.last_name }}
                        {{ profile_form.national_code}}
                    </div>
                    <div id="form-input-wrapper-2" class="w-100 justify-content-center flex-wrap" >
                        <div class="heading-wrapper d-lg-none text-center w-100">
                            <h2>تکمیلی</h2>
                        </div>
                        {{ profile_form.email_address }}
                        {{ profile_form.address}}
                        <label for="id_profile_pic">عکس پروفایل خود را بارگذاری کنید</label>
                        {{ profile_form.profile_pic }}
                    </div>
                    {% comment %} <div id="form-input-wrapper-3" class="w-100 justify-content-center flex-wrap">
                        <div class="heading-wrapper d-lg-none text-center w-100">
                            <h2>ضمانت</h2>
                        </div>
                        <select class="form-control px-4 py-2 mt-4 w-75" id="typePays" onchange="typeOfPays(this)">
                            <option value="default">انتخاب حالت پرداخت</option>
                            <option value="fish">ادامه با فیش حقوقی یا پروانه کسب</option>
                            <option value="document">ادامه با سند</option>
                            <option value="card">ادامه با کارت یارانه</option>
                        </select>
                        <label class="form-control px-4 py-2 mt-4 w-75" id="doc_input">
                            {{ payment_form.document }}
                            بارگذاری تصویر سند ملکی
                        </label>
                        <label class="form-control px-4 py-2 mt-4 w-75" id="fish_input">
                            <input type="file" class="d-none"/>
                            بارگذاری تصویر فیش حقوقی یا پروانه کسب
                        </label>
                    </div> {% endcomment %}
                    <div class="w-100 justify-content-center flex-wrap" id="form-input-wrapper-3">
                        <div class="heading-wrapper d-lg-none">
                            <h2>اطلاعات کارت</h2>
                        </div>
                        {{ payment_form.shaba }}
                        {{ payment_form.card }}
                    </div>
                    <div class="w-100 justify-content-center flex-wrap" id="form-input-wrapper-4">
                        <div class="heading-wrapper d-lg-none">
                            <h2>مقدار وام درخواستی</h2>
                        </div>
                        {{ payment_form.amount }}
                    </div>
                    <div class=" d-grid gap-2 w-75 mt-5">
                        <button type="button" id="continue-button" onclick="handleFormSteps('forward')" class="btn btn-success py-3">ادامه</button>
                        <button type="submit" id="submit-form" class="btn btn-primary py-3">ثبت و ارسال اطلاعات</button>
                        <button type="button" id="back-button" onclick="handleFormSteps('back')" class="btn btn-danger py-3">بازگشت</button>
                     </div>
                </form>
            </div>
        </div>
        <div class="image-wrapper col-lg-6 col-12 d-lg-flex d-none justify-content-center">
            <div style="position: absolute; top: 15rem;"><img src="/media/site/paven.svg" width="133" alt=""></div>
        </div>
    </div>
</div>

<div class="d-lg-block d-none steps-holder">
    <div class="p-3">
        <div class="w-100 py-2 px-4">درخواست وام</div>
        <div class="w-100 py-2 px-4">اطلاعات هویتی</div>
        <div class="w-100 py-2 px-4">اعتبارسنجی</div>
        <div class="w-100 py-2 px-4">پرداخت وام</div>
    </div>
</div>

{% endblock content %}

users/templates/profile.html
{% extends 'base.html' %}

{% block title %}پروفایل کاربر{% endblock title %}
{% block style %}
.avatar-container {
    width: max-content;
    height: max-content;
    display: block;
    float: left;
}
.heading-container {
    align-items: center !important;
}
.profile-table {
    width: 100%;
}

{% endblock style %}


{% block content %}
    <div class="container-lg px-5">
        <div class="p-5">
            <div class="d-flex">
                <div class="col-6 d-flex heading-container">
                    <h1>پروفایل</h1>
                </div>
                <div class="col-6">
                    <span class="avatar-container">
                    {% if user_.profile.profile_pic %}
                        <img src="{{ user_.profile.profile_pic.url }}" style="width: 118px;height: 118px;" class="rounded-circle"/>
                    {% else %} 
                        <img src="/media/site/avatar.svg" style="width: inherit"/>
                    {% endif %}
                    </span>
                </div>
            </div>
            <div>
                <table class="profile-table mt-5">
                    <tbody>
                        <tr>
                            <td>نام</td>
                            <td>{{ user_.profile.first_name }}</td>
                        </tr>
                        <tr>
                            <td>نام خانوادگی</td>
                            <td>{{ user_.profile.last_name }}</td>
                        </tr>
                        <tr>
                            <td>شماره ملی</td>
                            <td>{{ user_.profile.national_code }}</td>
                        </tr>
                        <tr>
                            <td>شماره موبایل</td>
                            <td>{{ user_.phone_number }}</td>
                        </tr>
                        <tr>
                            <td>آدرس ایمیل</td>
                            <td>{{ user_.profile.email_address }}</td>
                        </tr>
                        <tr>
                            <td>{{ user_.profile.address }}</td>
                            <td>
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                    مشاهده درخواست و اطلاعات پرداخت
                                  </button>
                                  
                                  <!-- Modal -->
                                  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <h1 class="modal-title fs-5" id="exampleModalLabel">مشاهده درخواست کاربر</h1>
                                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                          <table class="w-100">
                                            <tr>
                                                <td>شماره کارت</td>
                                                <td>{{ user_.payment.card }}</td>
                                            </tr>
                                            <tr>
                                                <td>شماره شبا</td>
                                                <td>{{ user_.payment.shaba }}</td>
                                            </tr>
                                            <tr>
                                                <td>مقدار وام درخواستی</td>
                                                <td>{{ user_.payment.amount }}</td>
                                            </tr>
                                          </table>
                                        </div>
                                        <div class="modal-footer">
                                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">بستن</button>
                                          {% if is_admin %}
                                          <button type="button" class="btn btn-primary">تایید درخواست</button>
                                          {% endif %}
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/requests.html
{% extends "base.html" %}

{% block title %}
    مدیریت درخواست ها
{% endblock title %}    

{% block content %}
  <div class="container-lg">
    <div class="p-3">
        <table class="w-100">
            <tr>
                <td>نام</td>
                <td>نام خانوادگی</td>
                <td>شماره همراه</td>
                <td>آدرس ایمیل</td>
                <td><a href="{% url 'export-csv-url' %}" class="btn btn-success" onclick="location.reload()">خروجی csv</a></td>
            </tr>
            {% for profile in profiles %}
                {% if profile.user.is_admin %}
                {% else %}
                <tr>
                    <td class="bordered">{{ profile.first_name }}</td>
                    <td class="bordered">{{ profile.last_name }}</td>
                    <td class="bordered">{{ profile.user.phone_number }}</td>
                    <td class="bordered">{{ profile.email_address }}</td>
                    <td class="bordered">
                        <a class="btn btn-primary" href="{% url 'user_detail_url' profile.user.id %}">
                            مشاهده
                        </a>
                        <a href="{% url 'delete_user_url' profile.user.id %}" class="btn btn-danger">حذف</a>
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </table>
    </div>
  </div>
{% endblock content %}

users/templates/signup.html
{% extends 'base.html' %}

{% block title %}ثبت نام در سایت{% endblock title %}

{% block style %}
#form-input-wrapper-1 {
    display: flex ;
}

#form-input-wrapper-2 {
    display: none ;
}

#form-input-wrapper-3 {
    display: none ;
}

#submit-form {
    display: none;
}

#back-button {
    display: none;
}

#doc_input, #fish_input, #card_wrapper {
    display: none;
}
{% endblock style %}

{% block content %}

<div class="container-lg">
    <div class="p-5 d-lg-flex">
        <div class="form-wrapper col-lg-6 col-12">
            <div class="heading-wrapper text-center w-100">
                <h1>ثبت نام</h1>
            </div>
            <div class="form-container mt-5">
                <form class="d-flex justify-content-center flex-wrap pe-5" method="post">
                    {% csrf_token %}
                    <div id="form-input-wrapper-1" class="w-100 justify-content-center flex-wrap">
                        {{ form.phone_number }}
                        {{ form.password }}
                    </div>
                    <div class=" d-grid gap-2 w-75 mt-5">
                        <button type="submit" id="continue-button" class="btn btn-primary py-3">ثبت نام</button>
                     </div>
                </form>
            </div>
        </div>
        <div class="image-wrapper col-lg-6 col-12 d-lg-flex d-none justify-content-center">
            <div style="position: absolute; top: 15rem;"><img src="/media/site/paven.svg" width="133" alt=""></div>
        </div>
    </div>
</div>

{% endblock content %}